package com.gdut.dongjun.domain.dao;

import com.gdut.dongjun.domain.po.BigGroupMapping;

public interface BigGroupMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_group_mapping
     *
     * @mbggenerated Tue Aug 01 21:06:42 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_group_mapping
     *
     * @mbggenerated Tue Aug 01 21:06:42 CST 2017
     */
    int insert(BigGroupMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_group_mapping
     *
     * @mbggenerated Tue Aug 01 21:06:42 CST 2017
     */
    int insertSelective(BigGroupMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_group_mapping
     *
     * @mbggenerated Tue Aug 01 21:06:42 CST 2017
     */
    BigGroupMapping selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_group_mapping
     *
     * @mbggenerated Tue Aug 01 21:06:42 CST 2017
     */
    int updateByPrimaryKeySelective(BigGroupMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_group_mapping
     *
     * @mbggenerated Tue Aug 01 21:06:42 CST 2017
     */
    int updateByPrimaryKey(BigGroupMapping record);
}