package com.gdut.dongjun.domain.dao;

import com.gdut.dongjun.domain.po.DeviceGroup;

public interface DeviceGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    int insert(DeviceGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    int insertSelective(DeviceGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    DeviceGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    int updateByPrimaryKeySelective(DeviceGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    int updateByPrimaryKey(DeviceGroup record);
}