package com.gdut.dongjun.domain.dao;

import com.gdut.dongjun.domain.po.DeviceGroupMapping;

public interface DeviceGroupMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_mapping
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_mapping
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    int insert(DeviceGroupMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_mapping
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    int insertSelective(DeviceGroupMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_mapping
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    DeviceGroupMapping selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_mapping
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    int updateByPrimaryKeySelective(DeviceGroupMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_mapping
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    int updateByPrimaryKey(DeviceGroupMapping record);
}