package com.gdut.dongjun.domain.dao;

import com.gdut.dongjun.domain.po.ElectronicModulePower;

public interface ElectronicModulePowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electronic_module_power
     *
     * @mbggenerated Tue May 02 16:49:22 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electronic_module_power
     *
     * @mbggenerated Tue May 02 16:49:22 CST 2017
     */
    int insert(ElectronicModulePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electronic_module_power
     *
     * @mbggenerated Tue May 02 16:49:22 CST 2017
     */
    int insertSelective(ElectronicModulePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electronic_module_power
     *
     * @mbggenerated Tue May 02 16:49:22 CST 2017
     */
    ElectronicModulePower selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electronic_module_power
     *
     * @mbggenerated Tue May 02 16:49:22 CST 2017
     */
    int updateByPrimaryKeySelective(ElectronicModulePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electronic_module_power
     *
     * @mbggenerated Tue May 02 16:49:22 CST 2017
     */
    int updateByPrimaryKey(ElectronicModulePower record);
}