package com.gdut.dongjun.domain.dao;

import com.gdut.dongjun.domain.po.LowVoltageSwitch;

public interface LowVoltageSwitchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table low_voltage_switch
     *
     * @mbggenerated Sun Feb 19 12:54:09 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table low_voltage_switch
     *
     * @mbggenerated Sun Feb 19 12:54:09 CST 2017
     */
    int insert(LowVoltageSwitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table low_voltage_switch
     *
     * @mbggenerated Sun Feb 19 12:54:09 CST 2017
     */
    int insertSelective(LowVoltageSwitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table low_voltage_switch
     *
     * @mbggenerated Sun Feb 19 12:54:09 CST 2017
     */
    LowVoltageSwitch selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table low_voltage_switch
     *
     * @mbggenerated Sun Feb 19 12:54:09 CST 2017
     */
    int updateByPrimaryKeySelective(LowVoltageSwitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table low_voltage_switch
     *
     * @mbggenerated Sun Feb 19 12:54:09 CST 2017
     */
    int updateByPrimaryKey(LowVoltageSwitch record);
}