package com.gdut.dongjun.domain.dao;

import com.gdut.dongjun.domain.po.PlatformGroup;

public interface PlatformGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_group
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_group
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    int insert(PlatformGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_group
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    int insertSelective(PlatformGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_group
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    PlatformGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_group
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    int updateByPrimaryKeySelective(PlatformGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_group
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    int updateByPrimaryKey(PlatformGroup record);
}