package com.gdut.dongjun.domain.dao;

import com.gdut.dongjun.domain.po.platform_group;

public interface platform_groupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_group
     *
     * @mbggenerated Thu Nov 03 08:48:41 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_group
     *
     * @mbggenerated Thu Nov 03 08:48:41 CST 2016
     */
    int insert(platform_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_group
     *
     * @mbggenerated Thu Nov 03 08:48:41 CST 2016
     */
    int insertSelective(platform_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_group
     *
     * @mbggenerated Thu Nov 03 08:48:41 CST 2016
     */
    platform_group selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_group
     *
     * @mbggenerated Thu Nov 03 08:48:41 CST 2016
     */
    int updateByPrimaryKeySelective(platform_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_group
     *
     * @mbggenerated Thu Nov 03 08:48:41 CST 2016
     */
    int updateByPrimaryKey(platform_group record);
}