package com.gdut.dongjun.domain.dao;

import com.gdut.dongjun.domain.po.TemperatureMeasure;

public interface TemperatureMeasureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temperature_measure
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temperature_measure
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    int insert(TemperatureMeasure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temperature_measure
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    int insertSelective(TemperatureMeasure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temperature_measure
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    TemperatureMeasure selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temperature_measure
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    int updateByPrimaryKeySelective(TemperatureMeasure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temperature_measure
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    int updateByPrimaryKey(TemperatureMeasure record);
}