package com.gdut.dongjun.domain.dao;

import com.gdut.dongjun.domain.po.UserLog;

public interface UserLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_log
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_log
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    int insert(UserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_log
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    int insertSelective(UserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_log
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    UserLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_log
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    int updateByPrimaryKeySelective(UserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_log
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    int updateByPrimaryKey(UserLog record);
}