package com.gdut.dongjun.domain.dao;

import com.gdut.dongjun.domain.po.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device_mapping
     *
     * @mbggenerated Mon Mar 06 21:45:46 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device_mapping
     *
     * @mbggenerated Mon Mar 06 21:45:46 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device_mapping
     *
     * @mbggenerated Mon Mar 06 21:45:46 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device_mapping
     *
     * @mbggenerated Mon Mar 06 21:45:46 CST 2017
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device_mapping
     *
     * @mbggenerated Mon Mar 06 21:45:46 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device_mapping
     *
     * @mbggenerated Mon Mar 06 21:45:46 CST 2017
     */
    int updateByPrimaryKey(User record);
}