package com.gdut.dongjun.domain.po;

public class DataMonitor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_monitor.id
     *
     * @mbggenerated Mon Apr 10 15:41:02 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_monitor.name
     *
     * @mbggenerated Mon Apr 10 15:41:02 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_monitor.address
     *
     * @mbggenerated Mon Apr 10 15:41:02 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_monitor.gourp_id
     *
     * @mbggenerated Mon Apr 10 15:41:02 CST 2017
     */
    private String gourpId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_monitor.id
     *
     * @return the value of data_monitor.id
     *
     * @mbggenerated Mon Apr 10 15:41:02 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_monitor.id
     *
     * @param id the value for data_monitor.id
     *
     * @mbggenerated Mon Apr 10 15:41:02 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_monitor.name
     *
     * @return the value of data_monitor.name
     *
     * @mbggenerated Mon Apr 10 15:41:02 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_monitor.name
     *
     * @param name the value for data_monitor.name
     *
     * @mbggenerated Mon Apr 10 15:41:02 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_monitor.address
     *
     * @return the value of data_monitor.address
     *
     * @mbggenerated Mon Apr 10 15:41:02 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_monitor.address
     *
     * @param address the value for data_monitor.address
     *
     * @mbggenerated Mon Apr 10 15:41:02 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_monitor.gourp_id
     *
     * @return the value of data_monitor.gourp_id
     *
     * @mbggenerated Mon Apr 10 15:41:02 CST 2017
     */
    public String getGourpId() {
        return gourpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_monitor.gourp_id
     *
     * @param gourpId the value for data_monitor.gourp_id
     *
     * @mbggenerated Mon Apr 10 15:41:02 CST 2017
     */
    public void setGourpId(String gourpId) {
        this.gourpId = gourpId;
    }
}