package com.gdut.dongjun.domain.po;

import java.util.Date;

public class ElectronicModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.id
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.name
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.address
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.device_number
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    private String deviceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.group_id
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.gmt_create
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.gmt_modified
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.id
     *
     * @return the value of electronic_module.id
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.id
     *
     * @param id the value for electronic_module.id
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.name
     *
     * @return the value of electronic_module.name
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.name
     *
     * @param name the value for electronic_module.name
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.address
     *
     * @return the value of electronic_module.address
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.address
     *
     * @param address the value for electronic_module.address
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.device_number
     *
     * @return the value of electronic_module.device_number
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.device_number
     *
     * @param deviceNumber the value for electronic_module.device_number
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.group_id
     *
     * @return the value of electronic_module.group_id
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.group_id
     *
     * @param groupId the value for electronic_module.group_id
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.gmt_create
     *
     * @return the value of electronic_module.gmt_create
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.gmt_create
     *
     * @param gmtCreate the value for electronic_module.gmt_create
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.gmt_modified
     *
     * @return the value of electronic_module.gmt_modified
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.gmt_modified
     *
     * @param gmtModified the value for electronic_module.gmt_modified
     *
     * @mbggenerated Tue May 02 15:40:31 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}