package com.gdut.dongjun.domain.po;

import java.util.Date;

public class ModuleInfoEvent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_info_event.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_info_event.module_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_info_event.monitor_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String monitorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_info_event.group_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_info_event.info
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_info_event.time
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_info_event.type
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_info_event.gmt_create
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_info_event.gmt_modified
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_info_event.id
     *
     * @return the value of module_info_event.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_info_event.id
     *
     * @param id the value for module_info_event.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_info_event.module_id
     *
     * @return the value of module_info_event.module_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_info_event.module_id
     *
     * @param moduleId the value for module_info_event.module_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_info_event.monitor_id
     *
     * @return the value of module_info_event.monitor_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getMonitorId() {
        return monitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_info_event.monitor_id
     *
     * @param monitorId the value for module_info_event.monitor_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setMonitorId(String monitorId) {
        this.monitorId = monitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_info_event.group_id
     *
     * @return the value of module_info_event.group_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_info_event.group_id
     *
     * @param groupId the value for module_info_event.group_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_info_event.info
     *
     * @return the value of module_info_event.info
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_info_event.info
     *
     * @param info the value for module_info_event.info
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_info_event.time
     *
     * @return the value of module_info_event.time
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_info_event.time
     *
     * @param time the value for module_info_event.time
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_info_event.type
     *
     * @return the value of module_info_event.type
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_info_event.type
     *
     * @param type the value for module_info_event.type
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_info_event.gmt_create
     *
     * @return the value of module_info_event.gmt_create
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_info_event.gmt_create
     *
     * @param gmtCreate the value for module_info_event.gmt_create
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_info_event.gmt_modified
     *
     * @return the value of module_info_event.gmt_modified
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_info_event.gmt_modified
     *
     * @param gmtModified the value for module_info_event.gmt_modified
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}