package com.gdut.dongjun.domain.po;

import java.util.Date;

public class ProtocolPort {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol_port.id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol_port.port
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol_port.remark
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol_port.gmt_create
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol_port.gmt_modified
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol_port.id
     *
     * @return the value of protocol_port.id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol_port.id
     *
     * @param id the value for protocol_port.id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol_port.port
     *
     * @return the value of protocol_port.port
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol_port.port
     *
     * @param port the value for protocol_port.port
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol_port.remark
     *
     * @return the value of protocol_port.remark
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol_port.remark
     *
     * @param remark the value for protocol_port.remark
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol_port.gmt_create
     *
     * @return the value of protocol_port.gmt_create
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol_port.gmt_create
     *
     * @param gmtCreate the value for protocol_port.gmt_create
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol_port.gmt_modified
     *
     * @return the value of protocol_port.gmt_modified
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol_port.gmt_modified
     *
     * @param gmtModified the value for protocol_port.gmt_modified
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}