package com.gdut.dongjun.domain.po;

public class UserDeviceMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device_mapping.id
     *
     * @mbggenerated Mon Apr 10 16:19:45 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device_mapping.device_id
     *
     * @mbggenerated Mon Apr 10 16:19:45 CST 2017
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device_mapping.user_id
     *
     * @mbggenerated Mon Apr 10 16:19:45 CST 2017
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device_mapping.id
     *
     * @return the value of user_device_mapping.id
     *
     * @mbggenerated Mon Apr 10 16:19:45 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device_mapping.id
     *
     * @param id the value for user_device_mapping.id
     *
     * @mbggenerated Mon Apr 10 16:19:45 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device_mapping.device_id
     *
     * @return the value of user_device_mapping.device_id
     *
     * @mbggenerated Mon Apr 10 16:19:45 CST 2017
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device_mapping.device_id
     *
     * @param deviceId the value for user_device_mapping.device_id
     *
     * @mbggenerated Mon Apr 10 16:19:45 CST 2017
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device_mapping.user_id
     *
     * @return the value of user_device_mapping.user_id
     *
     * @mbggenerated Mon Apr 10 16:19:45 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device_mapping.user_id
     *
     * @param userId the value for user_device_mapping.user_id
     *
     * @mbggenerated Mon Apr 10 16:19:45 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}