package com.gdut.dongjun.dao;

import com.gdut.dongjun.po.LowVoltageSwitch;

public interface LowVoltageSwitchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table low_voltage_switch
     *
     * @mbggenerated Thu May 25 17:25:15 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table low_voltage_switch
     *
     * @mbggenerated Thu May 25 17:25:15 CST 2017
     */
    int insert(LowVoltageSwitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table low_voltage_switch
     *
     * @mbggenerated Thu May 25 17:25:15 CST 2017
     */
    int insertSelective(LowVoltageSwitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table low_voltage_switch
     *
     * @mbggenerated Thu May 25 17:25:15 CST 2017
     */
    LowVoltageSwitch selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table low_voltage_switch
     *
     * @mbggenerated Thu May 25 17:25:15 CST 2017
     */
    int updateByPrimaryKeySelective(LowVoltageSwitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table low_voltage_switch
     *
     * @mbggenerated Thu May 25 17:25:15 CST 2017
     */
    int updateByPrimaryKey(LowVoltageSwitch record);
}