package com.gdut.dongjun.domain.po;

import java.util.Date;

import com.gdut.dongjun.domain.po.abstractmodel.AbstractBean;

public class ElectronicModuleHitchEvent extends AbstractBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module_hitch_event.id
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module_hitch_event.hitch_id
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    private String hitchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module_hitch_event.phase_a
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    private String phaseA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module_hitch_event.phase_b
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    private String phaseB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module_hitch_event.phase_c
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    private String phaseC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module_hitch_event.time_a
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    private String timeA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module_hitch_event.time_b
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    private String timeB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module_hitch_event.time_c
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    private String timeC;

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module_hitch_event.id
     *
     * @return the value of electronic_module_hitch_event.id
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module_hitch_event.id
     *
     * @param id the value for electronic_module_hitch_event.id
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module_hitch_event.hitch_id
     *
     * @return the value of electronic_module_hitch_event.hitch_id
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public String getHitchId() {
        return hitchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module_hitch_event.hitch_id
     *
     * @param hitchId the value for electronic_module_hitch_event.hitch_id
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public void setHitchId(String hitchId) {
        this.hitchId = hitchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module_hitch_event.phase_a
     *
     * @return the value of electronic_module_hitch_event.phase_a
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public String getPhaseA() {
        return phaseA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module_hitch_event.phase_a
     *
     * @param phaseA the value for electronic_module_hitch_event.phase_a
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public void setPhaseA(String phaseA) {
        this.phaseA = phaseA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module_hitch_event.phase_b
     *
     * @return the value of electronic_module_hitch_event.phase_b
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public String getPhaseB() {
        return phaseB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module_hitch_event.phase_b
     *
     * @param phaseB the value for electronic_module_hitch_event.phase_b
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public void setPhaseB(String phaseB) {
        this.phaseB = phaseB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module_hitch_event.phase_c
     *
     * @return the value of electronic_module_hitch_event.phase_c
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public String getPhaseC() {
        return phaseC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module_hitch_event.phase_c
     *
     * @param phaseC the value for electronic_module_hitch_event.phase_c
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public void setPhaseC(String phaseC) {
        this.phaseC = phaseC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module_hitch_event.time_a
     *
     * @return the value of electronic_module_hitch_event.time_a
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public String getTimeA() {
        return timeA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module_hitch_event.time_a
     *
     * @param timeA the value for electronic_module_hitch_event.time_a
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public void setTimeA(String timeA) {
        this.timeA = timeA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module_hitch_event.time_b
     *
     * @return the value of electronic_module_hitch_event.time_b
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public String getTimeB() {
        return timeB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module_hitch_event.time_b
     *
     * @param timeB the value for electronic_module_hitch_event.time_b
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public void setTimeB(String timeB) {
        this.timeB = timeB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module_hitch_event.time_c
     *
     * @return the value of electronic_module_hitch_event.time_c
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public String getTimeC() {
        return timeC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module_hitch_event.time_c
     *
     * @param timeC the value for electronic_module_hitch_event.time_c
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public void setTimeC(String timeC) {
        this.timeC = timeC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module_hitch_event.gmt_create
     *
     * @return the value of electronic_module_hitch_event.gmt_create
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module_hitch_event.gmt_create
     *
     * @param gmtCreate the value for electronic_module_hitch_event.gmt_create
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module_hitch_event.gmt_modified
     *
     * @return the value of electronic_module_hitch_event.gmt_modified
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module_hitch_event.gmt_modified
     *
     * @param gmtModified the value for electronic_module_hitch_event.gmt_modified
     *
     * @mbggenerated Wed May 03 17:23:26 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}