package com.gdut.dongjun.domain.po;

import java.util.Date;

public class ElectronicModule extends CommonBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.id
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.name
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.address
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.device_number
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    private String deviceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.company_id
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.del_tag
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    private Boolean delTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.gprs_id
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    private String gprsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.id
     *
     * @return the value of electronic_module.id
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.id
     *
     * @param id the value for electronic_module.id
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.name
     *
     * @return the value of electronic_module.name
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.name
     *
     * @param name the value for electronic_module.name
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.address
     *
     * @return the value of electronic_module.address
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.address
     *
     * @param address the value for electronic_module.address
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.device_number
     *
     * @return the value of electronic_module.device_number
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.device_number
     *
     * @param deviceNumber the value for electronic_module.device_number
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.company_id
     *
     * @return the value of electronic_module.company_id
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.company_id
     *
     * @param companyId the value for electronic_module.company_id
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.del_tag
     *
     * @return the value of electronic_module.del_tag
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    public Boolean getDelTag() {
        return delTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.del_tag
     *
     * @param delTag the value for electronic_module.del_tag
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    public void setDelTag(Boolean delTag) {
        this.delTag = delTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.gprs_id
     *
     * @return the value of electronic_module.gprs_id
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    public String getGprsId() {
        return gprsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.gprs_id
     *
     * @param gprsId the value for electronic_module.gprs_id
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    public void setGprsId(String gprsId) {
        this.gprsId = gprsId;
    }
}