package com.gdut.dongjun.domain.po;

public class PlatformGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_group.id
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_group.name
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_group.type
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_group.is_default
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    private Byte isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_group.company_id
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_group.group_id
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    private String groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_group.id
     *
     * @return the value of platform_group.id
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_group.id
     *
     * @param id the value for platform_group.id
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_group.name
     *
     * @return the value of platform_group.name
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_group.name
     *
     * @param name the value for platform_group.name
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_group.type
     *
     * @return the value of platform_group.type
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_group.type
     *
     * @param type the value for platform_group.type
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_group.is_default
     *
     * @return the value of platform_group.is_default
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    public Byte getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_group.is_default
     *
     * @param isDefault the value for platform_group.is_default
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    public void setIsDefault(Byte isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_group.company_id
     *
     * @return the value of platform_group.company_id
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_group.company_id
     *
     * @param companyId the value for platform_group.company_id
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_group.group_id
     *
     * @return the value of platform_group.group_id
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_group.group_id
     *
     * @param groupId the value for platform_group.group_id
     *
     * @mbggenerated Sun Feb 19 13:25:54 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }
}