package com.gdut.dongjun.domain.po;

import java.math.BigDecimal;
import java.util.Date;

public class TemperatureModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_module.id
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_module.name
     *	
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_module.address
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_module.sim_number
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    private String simNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_module.device_number
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    private String deviceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_module.online_time
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    private String onlineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_module.group_id
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_module.min_hitch_value
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    private BigDecimal minHitchValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_module.max_hitch_value
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    private BigDecimal maxHitchValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_module.gmt_create
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_module.gmt_modified
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_module.id
     *
     * @return the value of temperature_module.id
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_module.id
     *
     * @param id the value for temperature_module.id
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_module.name
     *
     * @return the value of temperature_module.name
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_module.name
     *
     * @param name the value for temperature_module.name
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_module.address
     *
     * @return the value of temperature_module.address
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_module.address
     *
     * @param address the value for temperature_module.address
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_module.sim_number
     *
     * @return the value of temperature_module.sim_number
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public String getSimNumber() {
        return simNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_module.sim_number
     *
     * @param simNumber the value for temperature_module.sim_number
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public void setSimNumber(String simNumber) {
        this.simNumber = simNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_module.device_number
     *
     * @return the value of temperature_module.device_number
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_module.device_number
     *
     * @param deviceNumber the value for temperature_module.device_number
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_module.online_time
     *
     * @return the value of temperature_module.online_time
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public String getOnlineTime() {
        return onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_module.online_time
     *
     * @param onlineTime the value for temperature_module.online_time
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public void setOnlineTime(String onlineTime) {
        this.onlineTime = onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_module.group_id
     *
     * @return the value of temperature_module.group_id
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_module.group_id
     *
     * @param groupId the value for temperature_module.group_id
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_module.min_hitch_value
     *
     * @return the value of temperature_module.min_hitch_value
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public BigDecimal getMinHitchValue() {
        return minHitchValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_module.min_hitch_value
     *
     * @param minHitchValue the value for temperature_module.min_hitch_value
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public void setMinHitchValue(BigDecimal minHitchValue) {
        this.minHitchValue = minHitchValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_module.max_hitch_value
     *
     * @return the value of temperature_module.max_hitch_value
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public BigDecimal getMaxHitchValue() {
        return maxHitchValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_module.max_hitch_value
     *
     * @param maxHitchValue the value for temperature_module.max_hitch_value
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public void setMaxHitchValue(BigDecimal maxHitchValue) {
        this.maxHitchValue = maxHitchValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_module.gmt_create
     *
     * @return the value of temperature_module.gmt_create
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_module.gmt_create
     *
     * @param gmtCreate the value for temperature_module.gmt_create
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_module.gmt_modified
     *
     * @return the value of temperature_module.gmt_modified
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_module.gmt_modified
     *
     * @param gmtModified the value for temperature_module.gmt_modified
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}