package com.gdut.dongjun.domain.po;

import java.util.Date;

import com.gdut.dongjun.domain.po.abstractmodel.AbstractBean;

public class TemperatureSensor extends AbstractBean {
	
    public TemperatureSensor() {
		super();
	}

	public TemperatureSensor(String id, Integer tag, String deviceId, String name) {
		super();
		this.id = id;
		this.tag = tag;
		this.deviceId = deviceId;
		this.name = name;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_sensor.id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_sensor.tag
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    private Integer tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_sensor.device_id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_sensor.name
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.id
     *
     * @return the value of temperature_sensor.id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.id
     *
     * @param id the value for temperature_sensor.id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.tag
     *
     * @return the value of temperature_sensor.tag
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public Integer getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.tag
     *
     * @param tag the value for temperature_sensor.tag
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setTag(Integer tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.device_id
     *
     * @return the value of temperature_sensor.device_id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.device_id
     *
     * @param deviceId the value for temperature_sensor.device_id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.name
     *
     * @return the value of temperature_sensor.name
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.name
     *
     * @param name the value for temperature_sensor.name
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.gmt_create
     *
     * @return the value of temperature_sensor.gmt_create
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.gmt_create
     *
     * @param gmtCreate the value for temperature_sensor.gmt_create
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.gmt_modified
     *
     * @return the value of temperature_sensor.gmt_modified
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.gmt_modified
     *
     * @param gmtModified the value for temperature_sensor.gmt_modified
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}