package com.gdut.dongjun.domain.po;

import java.math.BigDecimal;
import java.util.Date;

import com.gdut.dongjun.domain.po.abstractmodel.AbstractHitchEvent;

public class TemperatureMeasureHitchEvent extends AbstractHitchEvent {
	
	private String id;

	private String switchId;
	
	private String groupId;
	
	private Integer type;
	
	private String hitchTime;
	
	private String hitchReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_measure_hitch_event.value
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    private BigDecimal value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_measure_hitch_event.tag
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    private Integer tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_measure_hitch_event.gmt_create
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    private Date gmtCreate;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_measure_hitch_event.gmt_modified
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    private Date gmtModified;

    public TemperatureMeasureHitchEvent() {
		super();
	}

    public TemperatureMeasureHitchEvent(String id, String switchId, String groupId, Integer type, String hitchTime,
			String hitchReason, BigDecimal value, Integer tag, Date gmtCreate, Date gmtModified) {
		super();
		this.id = id;
		this.switchId = switchId;
		this.groupId = groupId;
		this.type = type;
		this.hitchTime = hitchTime;
		this.hitchReason = hitchReason;
		this.value = value;
		this.tag = tag;
		this.gmtCreate = gmtCreate;
		this.gmtModified = gmtModified;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_measure_hitch_event.id
     *
     * @return the value of temperature_measure_hitch_event.id
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_measure_hitch_event.id
     *
     * @param id the value for temperature_measure_hitch_event.id
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_measure_hitch_event.switch_id
     *
     * @return the value of temperature_measure_hitch_event.switch_id
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public String getSwitchId() {
        return switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_measure_hitch_event.switch_id
     *
     * @param switchId the value for temperature_measure_hitch_event.switch_id
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public void setSwitchId(String switchId) {
        this.switchId = switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_measure_hitch_event.value
     *
     * @return the value of temperature_measure_hitch_event.value
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_measure_hitch_event.value
     *
     * @param value the value for temperature_measure_hitch_event.value
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_measure_hitch_event.tag
     *
     * @return the value of temperature_measure_hitch_event.tag
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public Integer getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_measure_hitch_event.tag
     *
     * @param tag the value for temperature_measure_hitch_event.tag
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public void setTag(Integer tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_measure_hitch_event.hitch_reason
     *
     * @return the value of temperature_measure_hitch_event.hitch_reason
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public String getHitchReason() {
        return hitchReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_measure_hitch_event.hitch_reason
     *
     * @param hitchReason the value for temperature_measure_hitch_event.hitch_reason
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public void setHitchReason(String hitchReason) {
        this.hitchReason = hitchReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_measure_hitch_event.hitch_time
     *
     * @return the value of temperature_measure_hitch_event.hitch_time
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public String getHitchTime() {
        return hitchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_measure_hitch_event.hitch_time
     *
     * @param hitchTime the value for temperature_measure_hitch_event.hitch_time
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public void setHitchTime(String hitchTime) {
        this.hitchTime = hitchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_measure_hitch_event.group_id
     *
     * @return the value of temperature_measure_hitch_event.group_id
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_measure_hitch_event.group_id
     *
     * @param groupId the value for temperature_measure_hitch_event.group_id
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_measure_hitch_event.gmt_create
     *
     * @return the value of temperature_measure_hitch_event.gmt_create
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_measure_hitch_event.gmt_create
     *
     * @param gmtCreate the value for temperature_measure_hitch_event.gmt_create
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_measure_hitch_event.gmt_modified
     *
     * @return the value of temperature_measure_hitch_event.gmt_modified
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_measure_hitch_event.gmt_modified
     *
     * @param gmtModified the value for temperature_measure_hitch_event.gmt_modified
     *
     * @mbggenerated Sat Mar 04 10:13:25 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}
}