package com.gdut.dongjun.domain.po;

import java.util.Date;

import com.gdut.dongjun.domain.po.abstractmodel.AbstractBean;

public class UserLog extends AbstractBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.user_id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.type
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.date
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.company_id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    private String companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.id
     *
     * @return the value of user_log.id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.id
     *
     * @param id the value for user_log.id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.user_id
     *
     * @return the value of user_log.user_id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.user_id
     *
     * @param userId the value for user_log.user_id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.type
     *
     * @return the value of user_log.type
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.type
     *
     * @param type the value for user_log.type
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.date
     *
     * @return the value of user_log.date
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.date
     *
     * @param date the value for user_log.date
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.company_id
     *
     * @return the value of user_log.company_id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.company_id
     *
     * @param companyId the value for user_log.company_id
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.gmt_create
     *
     * @return the value of user_log.gmt_create
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.gmt_create
     *
     * @param gmtCreate the value for user_log.gmt_create
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.gmt_modified
     *
     * @return the value of user_log.gmt_modified
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.gmt_modified
     *
     * @param gmtModified the value for user_log.gmt_modified
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}