package com.gdut.dongjun.domain.po;

public class TemperatureDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_device.id
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_device.name
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_device.address
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_device.sim_number
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    private String simNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_device.device_number
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    private String deviceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_device.add_time
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    private String addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_device.available_time
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    private String availableTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_device.online_time
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    private String onlineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_device.group_id
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_device.min_hitch_value
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    private Long minHitchValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_device.max_hitch_value
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    private Long maxHitchValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_device.id
     *
     * @return the value of temperature_device.id
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_device.id
     *
     * @param id the value for temperature_device.id
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_device.name
     *
     * @return the value of temperature_device.name
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_device.name
     *
     * @param name the value for temperature_device.name
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_device.address
     *
     * @return the value of temperature_device.address
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_device.address
     *
     * @param address the value for temperature_device.address
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_device.sim_number
     *
     * @return the value of temperature_device.sim_number
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public String getSimNumber() {
        return simNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_device.sim_number
     *
     * @param simNumber the value for temperature_device.sim_number
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public void setSimNumber(String simNumber) {
        this.simNumber = simNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_device.device_number
     *
     * @return the value of temperature_device.device_number
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_device.device_number
     *
     * @param deviceNumber the value for temperature_device.device_number
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_device.add_time
     *
     * @return the value of temperature_device.add_time
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_device.add_time
     *
     * @param addTime the value for temperature_device.add_time
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_device.available_time
     *
     * @return the value of temperature_device.available_time
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public String getAvailableTime() {
        return availableTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_device.available_time
     *
     * @param availableTime the value for temperature_device.available_time
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public void setAvailableTime(String availableTime) {
        this.availableTime = availableTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_device.online_time
     *
     * @return the value of temperature_device.online_time
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public String getOnlineTime() {
        return onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_device.online_time
     *
     * @param onlineTime the value for temperature_device.online_time
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public void setOnlineTime(String onlineTime) {
        this.onlineTime = onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_device.group_id
     *
     * @return the value of temperature_device.group_id
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_device.group_id
     *
     * @param groupId the value for temperature_device.group_id
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_device.min_hitch_value
     *
     * @return the value of temperature_device.min_hitch_value
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public Long getMinHitchValue() {
        return minHitchValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_device.min_hitch_value
     *
     * @param minHitchValue the value for temperature_device.min_hitch_value
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public void setMinHitchValue(Long minHitchValue) {
        this.minHitchValue = minHitchValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_device.max_hitch_value
     *
     * @return the value of temperature_device.max_hitch_value
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public Long getMaxHitchValue() {
        return maxHitchValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_device.max_hitch_value
     *
     * @param maxHitchValue the value for temperature_device.max_hitch_value
     *
     * @mbggenerated Wed Mar 01 22:07:28 CST 2017
     */
    public void setMaxHitchValue(Long maxHitchValue) {
        this.maxHitchValue = maxHitchValue;
    }
}