package com.gdut.dongjun.domain.dao;

import com.gdut.dongjun.domain.po.PlatformGroup;

public interface PlatformGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Tue Nov 01 23:33:53 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Tue Nov 01 23:33:53 CST 2016
     */
    int insert(PlatformGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Tue Nov 01 23:33:53 CST 2016
     */
    int insertSelective(PlatformGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Tue Nov 01 23:33:53 CST 2016
     */
    PlatformGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Tue Nov 01 23:33:53 CST 2016
     */
    int updateByPrimaryKeySelective(PlatformGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Tue Nov 01 23:33:53 CST 2016
     */
    int updateByPrimaryKey(PlatformGroup record);
}