package com.gdut.dongjun.domain.po;

public class TemperatureSensor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_sensor.id
     *
     * @mbggenerated Sat Nov 26 13:44:08 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_sensor.tag
     *
     * @mbggenerated Sat Nov 26 13:44:08 CST 2016
     */
    private Integer tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_sensor.device_id
     *
     * @mbggenerated Sat Nov 26 13:44:08 CST 2016
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_sensor.name
     *
     * @mbggenerated Sat Nov 26 13:44:08 CST 2016
     */
    private String name;

    public TemperatureSensor() {
		super();
	}

	public TemperatureSensor(String id, Integer tag, String deviceId, String name) {
		super();
		this.id = id;
		this.tag = tag;
		this.deviceId = deviceId;
		this.name = name;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.id
     *
     * @return the value of temperature_sensor.id
     *
     * @mbggenerated Sat Nov 26 13:44:08 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.id
     *
     * @param id the value for temperature_sensor.id
     *
     * @mbggenerated Sat Nov 26 13:44:08 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.tag
     *
     * @return the value of temperature_sensor.tag
     *
     * @mbggenerated Sat Nov 26 13:44:08 CST 2016
     */
    public Integer getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.tag
     *
     * @param tag the value for temperature_sensor.tag
     *
     * @mbggenerated Sat Nov 26 13:44:08 CST 2016
     */
    public void setTag(Integer tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.device_id
     *
     * @return the value of temperature_sensor.device_id
     *
     * @mbggenerated Sat Nov 26 13:44:08 CST 2016
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.device_id
     *
     * @param deviceId the value for temperature_sensor.device_id
     *
     * @mbggenerated Sat Nov 26 13:44:08 CST 2016
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.name
     *
     * @return the value of temperature_sensor.name
     *
     * @mbggenerated Sat Nov 26 13:44:08 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.name
     *
     * @param name the value for temperature_sensor.name
     *
     * @mbggenerated Sat Nov 26 13:44:08 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}