package com.gdut.dongjun.po;

public class Center {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center.id
     *
     * @mbggenerated Thu Jul 13 16:20:08 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center.ip_addr
     *
     * @mbggenerated Thu Jul 13 16:20:08 CST 2017
     */
    private String ipAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center.company_id
     *
     * @mbggenerated Thu Jul 13 16:20:08 CST 2017
     */
    private String companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center.id
     *
     * @return the value of center.id
     *
     * @mbggenerated Thu Jul 13 16:20:08 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center.id
     *
     * @param id the value for center.id
     *
     * @mbggenerated Thu Jul 13 16:20:08 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center.ip_addr
     *
     * @return the value of center.ip_addr
     *
     * @mbggenerated Thu Jul 13 16:20:08 CST 2017
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center.ip_addr
     *
     * @param ipAddr the value for center.ip_addr
     *
     * @mbggenerated Thu Jul 13 16:20:08 CST 2017
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center.company_id
     *
     * @return the value of center.company_id
     *
     * @mbggenerated Thu Jul 13 16:20:08 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center.company_id
     *
     * @param companyId the value for center.company_id
     *
     * @mbggenerated Thu Jul 13 16:20:08 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
}