package com.gdut.dongjun.po;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.name
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.description
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.chief
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    private String chief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.address
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.phone
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.ip_addr
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    private String ipAddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.name
     *
     * @return the value of company.name
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.name
     *
     * @param name the value for company.name
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.description
     *
     * @return the value of company.description
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.description
     *
     * @param description the value for company.description
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.chief
     *
     * @return the value of company.chief
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    public String getChief() {
        return chief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.chief
     *
     * @param chief the value for company.chief
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    public void setChief(String chief) {
        this.chief = chief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.address
     *
     * @return the value of company.address
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.address
     *
     * @param address the value for company.address
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.phone
     *
     * @return the value of company.phone
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.phone
     *
     * @param phone the value for company.phone
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.ip_addr
     *
     * @return the value of company.ip_addr
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.ip_addr
     *
     * @param ipAddr the value for company.ip_addr
     *
     * @mbggenerated Mon Jul 17 15:46:12 CST 2017
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr;
    }
}