package com.gdut.dongjun.dto;

import com.gdut.dongjun.domain.po.GPRSModule;

public class GPRSModuleDTO {

	public GPRSModuleDTO() {
		super();
	}

	public GPRSModuleDTO(GPRSModule module, Integer status) {
		super();
		this.setId(module.getId());
		this.setName(module.getName());
		this.setAddress(module.getAddress());
		this.setAvailable(module.getAvailable());
		this.setDeviceNumber(module.getDeviceNumber());
		this.setGroupId(module.getGroupId());
		this.setStatus(status);
		this.setSimNumber(module.getSimNumber());
	}
	
	private String simNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gprs_module.id
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gprs_module.name
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gprs_module.address
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gprs_module.device_number
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	private String deviceNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gprs_module.group_id
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	private String groupId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gprs_module.available
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	private Boolean available;

	// 0不在线，1在线
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gprs_module.id
	 *
	 * @return the value of gprs_module.id
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gprs_module.id
	 *
	 * @param id
	 *            the value for gprs_module.id
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gprs_module.name
	 *
	 * @return the value of gprs_module.name
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gprs_module.name
	 *
	 * @param name
	 *            the value for gprs_module.name
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gprs_module.address
	 *
	 * @return the value of gprs_module.address
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gprs_module.address
	 *
	 * @param address
	 *            the value for gprs_module.address
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gprs_module.device_number
	 *
	 * @return the value of gprs_module.device_number
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	public String getDeviceNumber() {
		return deviceNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gprs_module.device_number
	 *
	 * @param deviceNumber
	 *            the value for gprs_module.device_number
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	public void setDeviceNumber(String deviceNumber) {
		this.deviceNumber = deviceNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gprs_module.group_id
	 *
	 * @return the value of gprs_module.group_id
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	public String getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gprs_module.group_id
	 *
	 * @param groupId
	 *            the value for gprs_module.group_id
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gprs_module.available
	 *
	 * @return the value of gprs_module.available
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	public Boolean getAvailable() {
		return available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gprs_module.available
	 *
	 * @param available
	 *            the value for gprs_module.available
	 *
	 * @mbggenerated Fri Mar 10 15:40:37 CST 2017
	 */
	public void setAvailable(Boolean available) {
		this.available = available;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getSimNumber() {
		return simNumber;
	}

	public void setSimNumber(String simNumber) {
		this.simNumber = simNumber;
	}
}
