package com.gdut.dongjun.service.cxf;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-12T11:17:10.327-04:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "HelloWorldImplService", 
                  wsdlLocation = "classpath:wsdl/hardware.wsdl",
                  targetNamespace = "http://cxf.service.dongjun.gdut.com/") 
public class HardwareServiceImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxf.service.dongjun.gdut.com/", "HelloWorldImplService");
    public final static QName HelloWorldImplPort = new QName("http://cxf.service.dongjun.gdut.com/", "HelloWorldImplPort");
    static {
        URL url = HardwareServiceImpl.class.getClassLoader().getResource("wsdl/hardware.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(HardwareServiceImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {1}", "classpath:wsdl/hardware.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public HardwareServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HardwareServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HardwareServiceImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HardwareServiceImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HardwareServiceImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HardwareServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldImplPort")
    public Hardware getHelloWorldImplPort() {
        return super.getPort(HelloWorldImplPort, Hardware.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldImplPort")
    public Hardware getHelloWorldImplPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldImplPort, Hardware.class, features);
    }

}