package com.gdut.dongjun.service.cxf;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.gdut.dongjun.service.cxf.po.HighVoltageStatus;
import com.gdut.dongjun.service.cxf.po.SwitchGPRS;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-12T11:17:10.288-04:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://cxf.service.dongjun.gdut.com/", name = "Hardware")
@XmlSeeAlso({ObjectFactory.class})
public interface Hardware {

    @WebMethod
    @RequestWrapper(localName = "generateOpenSwitchMessage", targetNamespace = "http://cxf.service.dongjun.gdut.com/", className = "com.gdut.dongjun.service.cxf.generateOpenSwitchMessage.GenerateOpenSwitchMessage")
    @ResponseWrapper(localName = "generateOpenSwitchMessageResponse", targetNamespace = "http://cxf.service.dongjun.gdut.com/", className = "com.gdut.dongjun.service.cxf.generateOpenSwitchMessage.GenerateOpenSwitchMessageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String generateOpenSwitchMessage (
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1 
    );
    
    @WebMethod
    @RequestWrapper(localName = "generateCloseSwitchMessage", targetNamespace = "http://cxf.service.dongjun.gdut.com/", className = "com.gdut.dongjun.service.cxf.generateCloseSwitchMessage.GenerateCloseSwitchMessage")
    @ResponseWrapper(localName = "generateCloseSwitchMessageResponse", targetNamespace = "http://cxf.service.dongjun.gdut.com/", className = "com.gdut.dongjun.service.cxf.generateCloseSwitchMessage.GenerateCloseSwitchMessageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String generateCloseSwitchMessage (
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1 
    );
    
    //public String getOnlineAddressById(String id);
    @WebMethod
    @RequestWrapper(localName = "getOnlineAddressById", targetNamespace = "http://cxf.service.dongjun.gdut.com/", className = "com.gdut.dongjun.service.cxf.getOnlineAddressById.GetOnlineAddressById")
    @ResponseWrapper(localName = "getOnlineAddressByIdResponse", targetNamespace = "http://cxf.service.dongjun.gdut.com/", className = "com.gdut.dongjun.service.cxf.getOnlineAddressById.GetOnlineAddressByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getOnlineAddressById (
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
    
    //public String getCtxInstance();
    @WebMethod
    @RequestWrapper(localName = "getCtxInstance", targetNamespace = "http://cxf.service.dongjun.gdut.com/", className = "com.gdut.dongjun.service.cxf.getCtxInstance.GetCtxInstance")
    @ResponseWrapper(localName = "getCtxInstanceResponse", targetNamespace = "http://cxf.service.dongjun.gdut.com/", className = "com.gdut.dongjun.service.cxf.getCtxInstance.GetCtxInstanceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public List<SwitchGPRS> getCtxInstance();
    
    //public String getSwitchGPRS(String id);
    @WebMethod
    @RequestWrapper(localName = "getSwitchGPRS", targetNamespace = "http://cxf.service.dongjun.gdut.com/", className = "com.gdut.dongjun.service.cxf.getSwitchGPRS.GetSwitchGPRS")
    @ResponseWrapper(localName = "getSwitchGPRSResponse", targetNamespace = "http://cxf.service.dongjun.gdut.com/", className = "com.gdut.dongjun.service.cxf.getSwitchGPRS.GetSwitchGPRSResponse")
    @WebResult(name = "return", targetNamespace = "")
    public SwitchGPRS getSwitchGPRS(
    	@WebParam(name = "arg0", targetNamespace = "")
    	String arg0
    );
    
    
    //public String getStatusbyId(String id);
    @WebMethod
    @Produces(MediaType.APPLICATION_JSON)
    @RequestWrapper(localName = "getStatusbyId", targetNamespace = "http://cxf.service.dongjun.gdut.com/", className = "com.gdut.dongjun.service.cxf.getStatusbyId.GetStatusbyId")
    @ResponseWrapper(localName = "getStatusbyIdResponse", targetNamespace = "http://cxf.service.dongjun.gdut.com/", className = "com.gdut.dongjun.service.cxf.getStatusbyId.GetStatusbyIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public HighVoltageStatus getStatusbyId(
    	@WebParam(name = "arg0", targetNamespace = "")
    	String arg0
    );
    
    //public boolean changeCtxOpen(String switchId);
    @WebMethod
    @Produces(MediaType.APPLICATION_JSON)
    @RequestWrapper(localName = "changeCtxOpen", targetNamespace = "http://cxf.service.dongjun.gdut.com/", className = "com.gdut.dongjun.service.cxf.changeCtxOpen.ChangeCtxOpen")
    @ResponseWrapper(localName = "changeCtxOpenResponse", targetNamespace = "http://cxf.service.dongjun.gdut.com/", className = "com.gdut.dongjun.service.cxf.changeCtxOpen.ChangeCtxOpenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean changeCtxOpen(
    	@WebParam(name = "arg0", targetNamespace = "")
    	String arg0
    );
}