package com.gdut.dongjun.domain.dao;

import com.gdut.dongjun.domain.dao.base.SinglePrimaryKeyBaseMapper;
import com.gdut.dongjun.domain.po.DataMonitorSubmodule;

public interface DataMonitorSubmoduleMapper extends SinglePrimaryKeyBaseMapper<DataMonitorSubmodule> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_monitor_submodule
     *
     * @mbggenerated Mon Apr 10 14:28:22 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_monitor_submodule
     *
     * @mbggenerated Mon Apr 10 14:28:22 CST 2017
     */
    int insert(DataMonitorSubmodule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_monitor_submodule
     *
     * @mbggenerated Mon Apr 10 14:28:22 CST 2017
     */
    int insertSelective(DataMonitorSubmodule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_monitor_submodule
     *
     * @mbggenerated Mon Apr 10 14:28:22 CST 2017
     */
    DataMonitorSubmodule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_monitor_submodule
     *
     * @mbggenerated Mon Apr 10 14:28:22 CST 2017
     */
    int updateByPrimaryKeySelective(DataMonitorSubmodule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_monitor_submodule
     *
     * @mbggenerated Mon Apr 10 14:28:22 CST 2017
     */
    int updateByPrimaryKey(DataMonitorSubmodule record);
}