package com.gdut.dongjun.domain.dao;

import com.gdut.dongjun.domain.dao.base.SinglePrimaryKeyBaseMapper;
import com.gdut.dongjun.domain.po.ElectronicModule;

public interface ElectronicModuleMapper extends SinglePrimaryKeyBaseMapper<ElectronicModule> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electronic_module
     *
     * @mbggenerated Mon Apr 10 14:56:33 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electronic_module
     *
     * @mbggenerated Mon Apr 10 14:56:33 CST 2017
     */
    int insert(ElectronicModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electronic_module
     *
     * @mbggenerated Mon Apr 10 14:56:33 CST 2017
     */
    int insertSelective(ElectronicModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electronic_module
     *
     * @mbggenerated Mon Apr 10 14:56:33 CST 2017
     */
    ElectronicModule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electronic_module
     *
     * @mbggenerated Mon Apr 10 14:56:33 CST 2017
     */
    int updateByPrimaryKeySelective(ElectronicModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electronic_module
     *
     * @mbggenerated Mon Apr 10 14:56:33 CST 2017
     */
    int updateByPrimaryKey(ElectronicModule record);
}