package com.gdut.dongjun.domain.po;

public class BigGroupMapping extends CommonBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_group_mapping.id
     *
     * @mbggenerated Tue Aug 01 21:06:42 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_group_mapping.group_id
     *
     * @mbggenerated Tue Aug 01 21:06:42 CST 2017
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_group_mapping.company_id
     *
     * @mbggenerated Tue Aug 01 21:06:42 CST 2017
     */
    private String companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_group_mapping.id
     *
     * @return the value of big_group_mapping.id
     *
     * @mbggenerated Tue Aug 01 21:06:42 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_group_mapping.id
     *
     * @param id the value for big_group_mapping.id
     *
     * @mbggenerated Tue Aug 01 21:06:42 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_group_mapping.group_id
     *
     * @return the value of big_group_mapping.group_id
     *
     * @mbggenerated Tue Aug 01 21:06:42 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_group_mapping.group_id
     *
     * @param groupId the value for big_group_mapping.group_id
     *
     * @mbggenerated Tue Aug 01 21:06:42 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_group_mapping.company_id
     *
     * @return the value of big_group_mapping.company_id
     *
     * @mbggenerated Tue Aug 01 21:06:42 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_group_mapping.company_id
     *
     * @param companyId the value for big_group_mapping.company_id
     *
     * @mbggenerated Tue Aug 01 21:06:42 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
}