package com.gdut.dongjun.domain.po;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.name
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.description
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.address
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.main_staff
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    private String mainStaff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.main_staff_id
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    private String mainStaffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.phone
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.email
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.name
     *
     * @return the value of company.name
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.name
     *
     * @param name the value for company.name
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.description
     *
     * @return the value of company.description
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.description
     *
     * @param description the value for company.description
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.address
     *
     * @return the value of company.address
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.address
     *
     * @param address the value for company.address
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.main_staff
     *
     * @return the value of company.main_staff
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public String getMainStaff() {
        return mainStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.main_staff
     *
     * @param mainStaff the value for company.main_staff
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public void setMainStaff(String mainStaff) {
        this.mainStaff = mainStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.main_staff_id
     *
     * @return the value of company.main_staff_id
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public String getMainStaffId() {
        return mainStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.main_staff_id
     *
     * @param mainStaffId the value for company.main_staff_id
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public void setMainStaffId(String mainStaffId) {
        this.mainStaffId = mainStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.phone
     *
     * @return the value of company.phone
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.phone
     *
     * @param phone the value for company.phone
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.email
     *
     * @return the value of company.email
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.email
     *
     * @param email the value for company.email
     *
     * @mbggenerated Sat Feb 18 18:17:15 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }
}