package com.gdut.dongjun.domain.po;

public class DeviceGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_group.id
     *
     * @mbggenerated Fri Nov 25 22:47:57 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_group.name
     *
     * @mbggenerated Fri Nov 25 22:47:57 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_group.platform_group_id
     *
     * @mbggenerated Fri Nov 25 22:47:57 CST 2016
     */
    private Integer platformGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_group.id
     *
     * @return the value of device_group.id
     *
     * @mbggenerated Fri Nov 25 22:47:57 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_group.id
     *
     * @param id the value for device_group.id
     *
     * @mbggenerated Fri Nov 25 22:47:57 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_group.name
     *
     * @return the value of device_group.name
     *
     * @mbggenerated Fri Nov 25 22:47:57 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_group.name
     *
     * @param name the value for device_group.name
     *
     * @mbggenerated Fri Nov 25 22:47:57 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_group.platform_group_id
     *
     * @return the value of device_group.platform_group_id
     *
     * @mbggenerated Fri Nov 25 22:47:57 CST 2016
     */
    public Integer getPlatformGroupId() {
        return platformGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_group.platform_group_id
     *
     * @param platformGroupId the value for device_group.platform_group_id
     *
     * @mbggenerated Fri Nov 25 22:47:57 CST 2016
     */
    public void setPlatformGroupId(Integer platformGroupId) {
        this.platformGroupId = platformGroupId;
    }
}