package com.gdut.dongjun.domain.po;

public class DeviceGroupMapping extends CommonBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_group_mapping.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_group_mapping.device_group_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String deviceGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_group_mapping.module_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_group_mapping.type
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_group_mapping.id
     *
     * @return the value of device_group_mapping.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_group_mapping.id
     *
     * @param id the value for device_group_mapping.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_group_mapping.device_group_id
     *
     * @return the value of device_group_mapping.device_group_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getDeviceGroupId() {
        return deviceGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_group_mapping.device_group_id
     *
     * @param deviceGroupId the value for device_group_mapping.device_group_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setDeviceGroupId(String deviceGroupId) {
        this.deviceGroupId = deviceGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_group_mapping.module_id
     *
     * @return the value of device_group_mapping.module_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_group_mapping.module_id
     *
     * @param moduleId the value for device_group_mapping.module_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_group_mapping.type
     *
     * @return the value of device_group_mapping.type
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_group_mapping.type
     *
     * @param type the value for device_group_mapping.type
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }
}