package com.gdut.dongjun.domain.po;

import java.util.Date;

public class ElectronicModule extends AbstractBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.id
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.name
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.address
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.device_number
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    private String deviceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.group_id
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.max_hitch_voltage
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    private Long maxHitchVoltage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.min_hitch_voltage
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    private Long minHitchVoltage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.max_hitch_current
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    private Long maxHitchCurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.min_hitch_current
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    private Long minHitchCurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.max_hitch_power
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    private Long maxHitchPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.min_hitch_power
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    private Long minHitchPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.gmt_create
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electronic_module.gmt_modified
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.id
     *
     * @return the value of electronic_module.id
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.id
     *
     * @param id the value for electronic_module.id
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.name
     *
     * @return the value of electronic_module.name
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.name
     *
     * @param name the value for electronic_module.name
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.address
     *
     * @return the value of electronic_module.address
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.address
     *
     * @param address the value for electronic_module.address
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.device_number
     *
     * @return the value of electronic_module.device_number
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.device_number
     *
     * @param deviceNumber the value for electronic_module.device_number
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.group_id
     *
     * @return the value of electronic_module.group_id
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.group_id
     *
     * @param groupId the value for electronic_module.group_id
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.max_hitch_voltage
     *
     * @return the value of electronic_module.max_hitch_voltage
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public Long getMaxHitchVoltage() {
        return maxHitchVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.max_hitch_voltage
     *
     * @param maxHitchVoltage the value for electronic_module.max_hitch_voltage
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public void setMaxHitchVoltage(Long maxHitchVoltage) {
        this.maxHitchVoltage = maxHitchVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.min_hitch_voltage
     *
     * @return the value of electronic_module.min_hitch_voltage
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public Long getMinHitchVoltage() {
        return minHitchVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.min_hitch_voltage
     *
     * @param minHitchVoltage the value for electronic_module.min_hitch_voltage
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public void setMinHitchVoltage(Long minHitchVoltage) {
        this.minHitchVoltage = minHitchVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.max_hitch_current
     *
     * @return the value of electronic_module.max_hitch_current
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public Long getMaxHitchCurrent() {
        return maxHitchCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.max_hitch_current
     *
     * @param maxHitchCurrent the value for electronic_module.max_hitch_current
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public void setMaxHitchCurrent(Long maxHitchCurrent) {
        this.maxHitchCurrent = maxHitchCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.min_hitch_current
     *
     * @return the value of electronic_module.min_hitch_current
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public Long getMinHitchCurrent() {
        return minHitchCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.min_hitch_current
     *
     * @param minHitchCurrent the value for electronic_module.min_hitch_current
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public void setMinHitchCurrent(Long minHitchCurrent) {
        this.minHitchCurrent = minHitchCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.max_hitch_power
     *
     * @return the value of electronic_module.max_hitch_power
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public Long getMaxHitchPower() {
        return maxHitchPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.max_hitch_power
     *
     * @param maxHitchPower the value for electronic_module.max_hitch_power
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public void setMaxHitchPower(Long maxHitchPower) {
        this.maxHitchPower = maxHitchPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.min_hitch_power
     *
     * @return the value of electronic_module.min_hitch_power
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public Long getMinHitchPower() {
        return minHitchPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.min_hitch_power
     *
     * @param minHitchPower the value for electronic_module.min_hitch_power
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public void setMinHitchPower(Long minHitchPower) {
        this.minHitchPower = minHitchPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.gmt_create
     *
     * @return the value of electronic_module.gmt_create
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.gmt_create
     *
     * @param gmtCreate the value for electronic_module.gmt_create
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electronic_module.gmt_modified
     *
     * @return the value of electronic_module.gmt_modified
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electronic_module.gmt_modified
     *
     * @param gmtModified the value for electronic_module.gmt_modified
     *
     * @mbggenerated Thu Apr 20 16:16:10 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}