package com.gdut.dongjun.domain.po;

public class GPRSModule extends CommonBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gprs_module.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gprs_module.name
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gprs_module.address
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gprs_module.sim_number
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String simNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gprs_module.device_number
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String deviceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gprs_module.company_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gprs_module.available
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private Boolean available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gprs_module.del_tag
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private Boolean delTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gprs_module.id
     *
     * @return the value of gprs_module.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gprs_module.id
     *
     * @param id the value for gprs_module.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gprs_module.name
     *
     * @return the value of gprs_module.name
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gprs_module.name
     *
     * @param name the value for gprs_module.name
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gprs_module.address
     *
     * @return the value of gprs_module.address
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gprs_module.address
     *
     * @param address the value for gprs_module.address
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gprs_module.sim_number
     *
     * @return the value of gprs_module.sim_number
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getSimNumber() {
        return simNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gprs_module.sim_number
     *
     * @param simNumber the value for gprs_module.sim_number
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setSimNumber(String simNumber) {
        this.simNumber = simNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gprs_module.device_number
     *
     * @return the value of gprs_module.device_number
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gprs_module.device_number
     *
     * @param deviceNumber the value for gprs_module.device_number
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gprs_module.company_id
     *
     * @return the value of gprs_module.company_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gprs_module.company_id
     *
     * @param companyId the value for gprs_module.company_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gprs_module.available
     *
     * @return the value of gprs_module.available
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gprs_module.available
     *
     * @param available the value for gprs_module.available
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gprs_module.del_tag
     *
     * @return the value of gprs_module.del_tag
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public Boolean getDelTag() {
        return delTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gprs_module.del_tag
     *
     * @param delTag the value for gprs_module.del_tag
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setDelTag(Boolean delTag) {
        this.delTag = delTag;
    }
}