package com.gdut.dongjun.domain.po;

import java.util.Date;

public class GPRSModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gprs_module.id
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gprs_module.address
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gprs_module.device_number
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    private String deviceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gprs_module.group_id
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gprs_module.available
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    private Boolean available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gprs_module.gmt_create
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gprs_module.gmt_modified
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gprs_module.id
     *
     * @return the value of gprs_module.id
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gprs_module.id
     *
     * @param id the value for gprs_module.id
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gprs_module.address
     *
     * @return the value of gprs_module.address
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gprs_module.address
     *
     * @param address the value for gprs_module.address
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gprs_module.device_number
     *
     * @return the value of gprs_module.device_number
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gprs_module.device_number
     *
     * @param deviceNumber the value for gprs_module.device_number
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gprs_module.group_id
     *
     * @return the value of gprs_module.group_id
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gprs_module.group_id
     *
     * @param groupId the value for gprs_module.group_id
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gprs_module.available
     *
     * @return the value of gprs_module.available
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gprs_module.available
     *
     * @param available the value for gprs_module.available
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gprs_module.gmt_create
     *
     * @return the value of gprs_module.gmt_create
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gprs_module.gmt_create
     *
     * @param gmtCreate the value for gprs_module.gmt_create
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gprs_module.gmt_modified
     *
     * @return the value of gprs_module.gmt_modified
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gprs_module.gmt_modified
     *
     * @param gmtModified the value for gprs_module.gmt_modified
     *
     * @mbggenerated Tue Mar 07 17:07:23 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}