package com.gdut.dongjun.domain.po;

import java.util.Date;

public class ModuleHitchEvent extends CommonBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_hitch_event.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_hitch_event.module_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_hitch_event.company_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_hitch_event.hitch_reason
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String hitchReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_hitch_event.hitch_time
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private Date hitchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_hitch_event.type
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_hitch_event.id
     *
     * @return the value of module_hitch_event.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_hitch_event.id
     *
     * @param id the value for module_hitch_event.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_hitch_event.module_id
     *
     * @return the value of module_hitch_event.module_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_hitch_event.module_id
     *
     * @param moduleId the value for module_hitch_event.module_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_hitch_event.company_id
     *
     * @return the value of module_hitch_event.company_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_hitch_event.company_id
     *
     * @param companyId the value for module_hitch_event.company_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_hitch_event.hitch_reason
     *
     * @return the value of module_hitch_event.hitch_reason
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getHitchReason() {
        return hitchReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_hitch_event.hitch_reason
     *
     * @param hitchReason the value for module_hitch_event.hitch_reason
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setHitchReason(String hitchReason) {
        this.hitchReason = hitchReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_hitch_event.hitch_time
     *
     * @return the value of module_hitch_event.hitch_time
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public Date getHitchTime() {
        return hitchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_hitch_event.hitch_time
     *
     * @param hitchTime the value for module_hitch_event.hitch_time
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setHitchTime(Date hitchTime) {
        this.hitchTime = hitchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_hitch_event.type
     *
     * @return the value of module_hitch_event.type
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_hitch_event.type
     *
     * @param type the value for module_hitch_event.type
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }
}