package com.gdut.dongjun.domain.po;

public class PersistentHitchMessage extends CommonBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_hitch_message.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_hitch_message.type
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_hitch_message.hitch_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String hitchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_hitch_message.company_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_hitch_message.user_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_hitch_message.id
     *
     * @return the value of persistent_hitch_message.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_hitch_message.id
     *
     * @param id the value for persistent_hitch_message.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_hitch_message.type
     *
     * @return the value of persistent_hitch_message.type
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_hitch_message.type
     *
     * @param type the value for persistent_hitch_message.type
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_hitch_message.hitch_id
     *
     * @return the value of persistent_hitch_message.hitch_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getHitchId() {
        return hitchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_hitch_message.hitch_id
     *
     * @param hitchId the value for persistent_hitch_message.hitch_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setHitchId(String hitchId) {
        this.hitchId = hitchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_hitch_message.company_id
     *
     * @return the value of persistent_hitch_message.company_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_hitch_message.company_id
     *
     * @param companyId the value for persistent_hitch_message.company_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_hitch_message.user_id
     *
     * @return the value of persistent_hitch_message.user_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_hitch_message.user_id
     *
     * @param userId the value for persistent_hitch_message.user_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}