package com.gdut.dongjun.domain.po;

import java.util.Date;

public class PersistentHitchMessage extends AbstractBean {
	
    public PersistentHitchMessage() {
		super();
	}

	public PersistentHitchMessage(String id, Integer type, String hitchId, String groupId, String userId,
			String monitorId) {
		super();
		this.id = id;
		this.type = type;
		this.hitchId = hitchId;
		this.groupId = groupId;
		this.userId = userId;
		this.monitorId = monitorId;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_hitch_message.id
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_hitch_message.type
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_hitch_message.hitch_id
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    private String hitchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_hitch_message.group_id
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_hitch_message.user_id
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_hitch_message.monitor_id
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    private String monitorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_hitch_message.id
     *
     * @return the value of persistent_hitch_message.id
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_hitch_message.id
     *
     * @param id the value for persistent_hitch_message.id
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_hitch_message.type
     *
     * @return the value of persistent_hitch_message.type
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_hitch_message.type
     *
     * @param type the value for persistent_hitch_message.type
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_hitch_message.hitch_id
     *
     * @return the value of persistent_hitch_message.hitch_id
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public String getHitchId() {
        return hitchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_hitch_message.hitch_id
     *
     * @param hitchId the value for persistent_hitch_message.hitch_id
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public void setHitchId(String hitchId) {
        this.hitchId = hitchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_hitch_message.group_id
     *
     * @return the value of persistent_hitch_message.group_id
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_hitch_message.group_id
     *
     * @param groupId the value for persistent_hitch_message.group_id
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_hitch_message.user_id
     *
     * @return the value of persistent_hitch_message.user_id
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_hitch_message.user_id
     *
     * @param userId the value for persistent_hitch_message.user_id
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_hitch_message.monitor_id
     *
     * @return the value of persistent_hitch_message.monitor_id
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public String getMonitorId() {
        return monitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_hitch_message.monitor_id
     *
     * @param monitorId the value for persistent_hitch_message.monitor_id
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public void setMonitorId(String monitorId) {
        this.monitorId = monitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_hitch_message.gmt_create
     *
     * @return the value of persistent_hitch_message.gmt_create
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_hitch_message.gmt_create
     *
     * @param gmtCreate the value for persistent_hitch_message.gmt_create
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_hitch_message.gmt_modified
     *
     * @return the value of persistent_hitch_message.gmt_modified
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_hitch_message.gmt_modified
     *
     * @param gmtModified the value for persistent_hitch_message.gmt_modified
     *
     * @mbggenerated Thu Apr 20 18:34:36 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}