package com.gdut.dongjun.domain.po;

public class PlatformGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_group.id
     *
     * @mbggenerated Tue Oct 18 22:08:07 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_group.name
     *
     * @mbggenerated Tue Oct 18 22:08:07 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_group.type
     *
     * @mbggenerated Tue Oct 18 22:08:07 CST 2016
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_group.is_default
     *
     * @mbggenerated Tue Oct 18 22:08:07 CST 2016
     */
    private Byte isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_group.company_id
     *
     * @mbggenerated Tue Oct 18 22:08:07 CST 2016
     */
    private String companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_group.id
     *
     * @return the value of platform_group.id
     *
     * @mbggenerated Tue Oct 18 22:08:07 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_group.id
     *
     * @param id the value for platform_group.id
     *
     * @mbggenerated Tue Oct 18 22:08:07 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_group.name
     *
     * @return the value of platform_group.name
     *
     * @mbggenerated Tue Oct 18 22:08:07 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_group.name
     *
     * @param name the value for platform_group.name
     *
     * @mbggenerated Tue Oct 18 22:08:07 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_group.type
     *
     * @return the value of platform_group.type
     *
     * @mbggenerated Tue Oct 18 22:08:07 CST 2016
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_group.type
     *
     * @param type the value for platform_group.type
     *
     * @mbggenerated Tue Oct 18 22:08:07 CST 2016
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_group.is_default
     *
     * @return the value of platform_group.is_default
     *
     * @mbggenerated Tue Oct 18 22:08:07 CST 2016
     */
    public Byte getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_group.is_default
     *
     * @param isDefault the value for platform_group.is_default
     *
     * @mbggenerated Tue Oct 18 22:08:07 CST 2016
     */
    public void setIsDefault(Byte isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_group.company_id
     *
     * @return the value of platform_group.company_id
     *
     * @mbggenerated Tue Oct 18 22:08:07 CST 2016
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_group.company_id
     *
     * @param companyId the value for platform_group.company_id
     *
     * @mbggenerated Tue Oct 18 22:08:07 CST 2016
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
}