package com.gdut.dongjun.domain.po;

public class ProtocolPort {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol_port.id
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol_port.lv_port
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    private Integer lvPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol_port.hv_port
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    private Integer hvPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol_port.con_port
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    private Integer conPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol_port.tem_port
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    private Integer temPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column protocol_port.hv1_3_port
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    private Integer hv13Port;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol_port.id
     *
     * @return the value of protocol_port.id
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol_port.id
     *
     * @param id the value for protocol_port.id
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol_port.lv_port
     *
     * @return the value of protocol_port.lv_port
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    public Integer getLvPort() {
        return lvPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol_port.lv_port
     *
     * @param lvPort the value for protocol_port.lv_port
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    public void setLvPort(Integer lvPort) {
        this.lvPort = lvPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol_port.hv_port
     *
     * @return the value of protocol_port.hv_port
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    public Integer getHvPort() {
        return hvPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol_port.hv_port
     *
     * @param hvPort the value for protocol_port.hv_port
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    public void setHvPort(Integer hvPort) {
        this.hvPort = hvPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol_port.con_port
     *
     * @return the value of protocol_port.con_port
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    public Integer getConPort() {
        return conPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol_port.con_port
     *
     * @param conPort the value for protocol_port.con_port
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    public void setConPort(Integer conPort) {
        this.conPort = conPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol_port.tem_port
     *
     * @return the value of protocol_port.tem_port
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    public Integer getTemPort() {
        return temPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol_port.tem_port
     *
     * @param temPort the value for protocol_port.tem_port
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    public void setTemPort(Integer temPort) {
        this.temPort = temPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column protocol_port.hv1_3_port
     *
     * @return the value of protocol_port.hv1_3_port
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    public Integer getHv13Port() {
        return hv13Port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column protocol_port.hv1_3_port
     *
     * @param hv13Port the value for protocol_port.hv1_3_port
     *
     * @mbggenerated Wed Oct 26 21:20:34 CST 2016
     */
    public void setHv13Port(Integer hv13Port) {
        this.hv13Port = hv13Port;
    }
}