package com.gdut.dongjun.domain.po;

public class TemperatureSensor extends CommonBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_sensor.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_sensor.tag
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private Integer tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_sensor.type
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_sensor.module_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_sensor.name
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temperature_sensor.del_tag
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    private Boolean delTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.id
     *
     * @return the value of temperature_sensor.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.id
     *
     * @param id the value for temperature_sensor.id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.tag
     *
     * @return the value of temperature_sensor.tag
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public Integer getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.tag
     *
     * @param tag the value for temperature_sensor.tag
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setTag(Integer tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.type
     *
     * @return the value of temperature_sensor.type
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.type
     *
     * @param type the value for temperature_sensor.type
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.module_id
     *
     * @return the value of temperature_sensor.module_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.module_id
     *
     * @param moduleId the value for temperature_sensor.module_id
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.name
     *
     * @return the value of temperature_sensor.name
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.name
     *
     * @param name the value for temperature_sensor.name
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temperature_sensor.del_tag
     *
     * @return the value of temperature_sensor.del_tag
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public Boolean getDelTag() {
        return delTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temperature_sensor.del_tag
     *
     * @param delTag the value for temperature_sensor.del_tag
     *
     * @mbggenerated Sat Jul 29 15:30:24 CST 2017
     */
    public void setDelTag(Boolean delTag) {
        this.delTag = delTag;
    }
}