package com.gdut.dongjun.domain.po;

public class User extends CommonBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.real_name
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.control_code
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    private String controlCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.company_id
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.available
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    private Integer available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.del_tag
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    private Boolean delTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.real_name
     *
     * @return the value of user.real_name
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.real_name
     *
     * @param realName the value for user.real_name
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.control_code
     *
     * @return the value of user.control_code
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public String getControlCode() {
        return controlCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.control_code
     *
     * @param controlCode the value for user.control_code
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public void setControlCode(String controlCode) {
        this.controlCode = controlCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.company_id
     *
     * @return the value of user.company_id
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.company_id
     *
     * @param companyId the value for user.company_id
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.available
     *
     * @return the value of user.available
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public Integer getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.available
     *
     * @param available the value for user.available
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public void setAvailable(Integer available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.del_tag
     *
     * @return the value of user.del_tag
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public Boolean getDelTag() {
        return delTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.del_tag
     *
     * @param delTag the value for user.del_tag
     *
     * @mbggenerated Sat Jul 29 16:02:42 CST 2017
     */
    public void setDelTag(Boolean delTag) {
        this.delTag = delTag;
    }
}