package com.gdut.dongjun.dao;

import com.gdut.dongjun.po.Line;

public interface LineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbggenerated Wed Jul 19 13:05:32 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbggenerated Wed Jul 19 13:05:32 CST 2017
     */
    int insert(Line record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbggenerated Wed Jul 19 13:05:32 CST 2017
     */
    int insertSelective(Line record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbggenerated Wed Jul 19 13:05:32 CST 2017
     */
    Line selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbggenerated Wed Jul 19 13:05:32 CST 2017
     */
    int updateByPrimaryKeySelective(Line record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbggenerated Wed Jul 19 13:05:32 CST 2017
     */
    int updateByPrimaryKey(Line record);
}