package com.gdut.dongjun.domain.dao;

import com.gdut.dongjun.domain.po.ModuleHitchEvent;

public interface ModuleHitchEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_hitch_event
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_hitch_event
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    int insert(ModuleHitchEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_hitch_event
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    int insertSelective(ModuleHitchEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_hitch_event
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    ModuleHitchEvent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_hitch_event
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    int updateByPrimaryKeySelective(ModuleHitchEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_hitch_event
     *
     * @mbggenerated Mon Aug 07 15:59:07 CST 2017
     */
    int updateByPrimaryKey(ModuleHitchEvent record);
}