package com.gdut.dongjun.domain.dao;

import com.gdut.dongjun.domain.po.TemperatureModule;

public interface TemperatureModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temperature_module
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temperature_module
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    int insert(TemperatureModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temperature_module
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    int insertSelective(TemperatureModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temperature_module
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    TemperatureModule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temperature_module
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    int updateByPrimaryKeySelective(TemperatureModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temperature_module
     *
     * @mbggenerated Mon Apr 10 23:08:39 CST 2017
     */
    int updateByPrimaryKey(TemperatureModule record);
}