package com.gdut.dongjun.domain.po.authc;

import java.util.Date;

public class UserRole extends UserRoleKey {

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.gmt_create
     *
     * @return the value of user_role.gmt_create
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.gmt_create
     *
     * @param gmtCreate the value for user_role.gmt_create
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.gmt_modified
     *
     * @return the value of user_role.gmt_modified
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.gmt_modified
     *
     * @param gmtModified the value for user_role.gmt_modified
     *
     * @mbggenerated Thu Apr 13 21:13:41 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}