package com.gdut.dongjun.domain.po;

public class HighSwitchUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_switch_user.id
     *
     * @mbggenerated Wed May 04 15:45:52 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_switch_user.user_id
     *
     * @mbggenerated Wed May 04 15:45:52 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_switch_user.high_voltage_switch_id
     *
     * @mbggenerated Wed May 04 15:45:52 CST 2016
     */
    private String highVoltageSwitchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_switch_user.id
     *
     * @return the value of high_switch_user.id
     *
     * @mbggenerated Wed May 04 15:45:52 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_switch_user.id
     *
     * @param id the value for high_switch_user.id
     *
     * @mbggenerated Wed May 04 15:45:52 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_switch_user.user_id
     *
     * @return the value of high_switch_user.user_id
     *
     * @mbggenerated Wed May 04 15:45:52 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_switch_user.user_id
     *
     * @param userId the value for high_switch_user.user_id
     *
     * @mbggenerated Wed May 04 15:45:52 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_switch_user.high_voltage_switch_id
     *
     * @return the value of high_switch_user.high_voltage_switch_id
     *
     * @mbggenerated Wed May 04 15:45:52 CST 2016
     */
    public String getHighVoltageSwitchId() {
        return highVoltageSwitchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_switch_user.high_voltage_switch_id
     *
     * @param highVoltageSwitchId the value for high_switch_user.high_voltage_switch_id
     *
     * @mbggenerated Wed May 04 15:45:52 CST 2016
     */
    public void setHighVoltageSwitchId(String highVoltageSwitchId) {
        this.highVoltageSwitchId = highVoltageSwitchId;
    }
}